name: 'Setup Cygwin for a GAP installation'
description: 'Download and install Cygwin such that GAP can be installed afterwards'
inputs:
  pkgs-to-install:
    description: 'Comma-separated list containing the Cygwin packages needed to install GAP'
    required: false
    default: 'wget,git,gcc-g++,gcc-core,libgmp-devel,make,libtool,autoconf,zlib-devel,libreadline-devel,xdg-utils'
  extra-pkgs-to-install:
    description: 'Comma-separated list containing the extra Cygwin packages needed to install additional packages'
    required: false
    default: ''
    
runs:
  using: "composite"
  steps:

    - name: "Configure git autocrlf to input"
      shell: cmd
      run: git config --global core.autocrlf input

    - name: "Download and install Cygwin"
      uses: cygwin/cygwin-install-action@v5
      with:
        packages: "${{ inputs.pkgs-to-install}},${{ inputs.extra-pkgs-to-install }}"
        add-to-path: false
        install-dir: C:\cygwin64

    - name: "Add bash with correct options to PATH"
      shell: powershell
      run: |
        mkdir C:\cygwin-bash-folder
        $executable = @"
        @echo off
        set CHERE_INVOKING=1
        for %%a in (%*) do set file=%%a
        C:\cygwin64\bin\bash.exe --login --norc -e -o pipefail -o igncr %file%
        exit /b %errorlevel%
        "@
        Set-Content C:\cygwin-bash-folder\bash.bat $executable -Encoding utf8 
        echo "C:\cygwin-bash-folder" >> $env:GITHUB_PATH
    
    # cygwin provides 'make' but not 'gmake', and there is another executable called 'gmake' elsewhere in the windows build.
    - name: "Set up 'gmake' symlink"
      shell: bash
      run: ln -s /usr/bin/make /usr/bin/gmake
