name: CI

# Trigger the workflow on push to master / main, or on pull request
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    strategy:
      fail-fast: false
      matrix:
        extra-pkgs: ['', 'vim']

    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          extra-pkgs-to-install: ${{ matrix.extra-pkgs }}
